### PR TITLE
Cleaning

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by navanchauhan** [comment]
Hiya @ericgaspar! Thanks for the help. 

The reason I do not create a data dir is because the app needs to generate the frontend and static files every time according to the manual install / upgrade

I do like your timezone commit though, are you okay with me removing the creation/deletion of data dir and merging the PR then?

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
Tested upgrade manually and it worked 

!ttestme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Comment by navanchauhan** [comment]
!testme

**Pull request merged**
